name: Continuous Delivery Wokflows
on:
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Simulando Continuous Delivery
        uses: action/upload-artifact@v4
        with:
          name: projeitozipado.zip
          path:
            '**.py'
            README.md

