name: Continuous Delivery Wokflows
on:
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: action/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            main.py
            README.md

